"""Compute every pre-registered number from results/*.jsonl and write results/RESULTS.md.

Nothing in RESULTS.md is typed by hand: re-run this script to regenerate it.
"""
import json
import os
import random
import re

from fse.ingest import ROOT
from fse.judge import strip_confidence
from fse.metrics import aurac, auroc_for_errors, cluster_entropy, selective_accuracy

RES = ROOT / os.environ.get("FSE_RESULTS", "results")
N_BOOT = 2000
SEED = 7


def load(name):
    path = RES / name
    return {r["id"]: r for r in map(json.loads, path.open(encoding="utf-8"))} if path.exists() else {}


def normalise(text):
    """Lexical-entropy key: case, whitespace and number formatting removed; confidence line dropped."""
    t = strip_confidence(text)[0].lower()
    t = re.sub(r"(?<=\d),(?=\d{3})", "", t)            # 1,577 -> 1577
    t = re.sub(r"\$\s*", "$", t)
    return re.sub(r"[\s.]+$", "", re.sub(r"\s+", " ", t)).strip()


def boot_ci(fn, n, seed=SEED):
    """95% percentile bootstrap over question indices; fn(idx) -> statistic (None if undefined)."""
    rng = random.Random(seed)
    vals = []
    for _ in range(N_BOOT):
        v = fn([rng.randrange(n) for _ in range(n)])
        if v is not None:
            vals.append(v)
    vals.sort()
    return vals[int(0.025 * len(vals))], vals[int(0.975 * len(vals)) - 1], len(vals)


def safe_auroc(scores, wrong):
    return auroc_for_errors(scores, wrong) if 0 < sum(wrong) < len(wrong) else None


def main():
    gen, jud, laya = load("generations.jsonl"), load("judgements.jsonl"), load("laya.jsonl")
    ids = [i for i in gen if i in jud]
    rows = []
    for i in ids:
        g, j = gen[i], jud[i]
        answer, conf = strip_confidence(g["greedy"])
        rows.append({
            "id": i, "label": j["grade"]["label"], "hit": g["evidence_hit"],
            "se": cluster_entropy(j["clusters"]),
            "lex": cluster_entropy([normalise(s) for s in g["samples"]]),
            "verbal": 100 - (conf if conf is not None else 50), "conf_missing": conf is None,
            "retr": -g["dense_top1"], "length": len(answer),
            "laya": (1 - laya[i]["supported"]) if i in laya else None,
        })
    n_all = len(rows)
    labels = {k: sum(r["label"] == k for r in rows) for k in ("correct", "incorrect", "failed")}
    ans = [r for r in rows if r["label"] != "failed"]
    wrong = [r["label"] == "incorrect" for r in ans]
    methods = [("Semantic entropy (primary)", "se"), ("Lexical entropy", "lex"),
               ("Verbalised confidence", "verbal"), ("Trivial: retrieval similarity", "retr"),
               ("Trivial: answer length", "length")]
    if all(r["laya"] is not None for r in ans):
        methods.append(("Exploratory: Laya grounding", "laya"))

    out = ["# Results (generated by `python -m fse.analyse`; do not edit by hand)", ""]
    out.append(f"Questions with generation and judgement: **{n_all} of 150**.")
    out.append(f"Greedy labels: correct {labels['correct']}, incorrect {labels['incorrect']}, "
               f"failed to answer {labels['failed']} "
               f"({labels['correct'] / n_all:.1%} / {labels['incorrect'] / n_all:.1%} / {labels['failed'] / n_all:.1%}).")
    hits = sum(r["hit"] for r in rows)
    out.append(f"Evidence-page recall@5 (hybrid): {hits} of {n_all} ({hits / n_all:.1%}).")
    miss_wrong = sum(1 for r in ans if r["label"] == "incorrect" and not r["hit"])
    if labels["incorrect"]:
        out.append(f"Incorrect answers whose top 5 missed every gold page: {miss_wrong} of {labels['incorrect']}.")
    missing_conf = sum(r["conf_missing"] for r in rows)
    out.append(f"Greedy answers with no parseable confidence (scored as 50): {missing_conf}.")
    void = []
    if labels["correct"] < 20 or labels["incorrect"] < 20:
        void.append(f"fewer than 20 correct or incorrect answered ({labels['correct']} / {labels['incorrect']})")
    if n_all < 135:
        void.append(f"more than 10% of questions missing ({150 - n_all})")
    out.append("")
    out.append("**VOID: " + "; ".join(void) + "**" if void else "Void checks passed (judge audit reported separately).")
    out.append("")
    out.append(f"## AUROC at flagging incorrect answers (answered only: {len(ans)}; incorrect {sum(wrong)})")
    out.append("")
    out.append("| Score | AUROC | 95% CI | AURAC | Acc @50% | Acc @70% | Acc @90% |")
    out.append("|---|---|---|---|---|---|---|")
    correct = [not w for w in wrong]
    base_acc = sum(correct) / len(correct) if correct else 0
    for name, key in methods:
        s = [r[key] for r in ans]
        a = safe_auroc(s, wrong)
        lo, hi, _ = boot_ci(lambda idx: safe_auroc([s[k] for k in idx], [wrong[k] for k in idx]), len(ans))
        out.append(f"| {name} | {a:.3f} | {lo:.3f} to {hi:.3f} | {aurac(s, correct):.3f} | "
                   f"{selective_accuracy(s, correct, 0.5):.1%} | {selective_accuracy(s, correct, 0.7):.1%} | "
                   f"{selective_accuracy(s, correct, 0.9):.1%} |")
    out.append(f"\nAccuracy among answered at full coverage: {base_acc:.1%}. Chance AUROC is 0.500.")
    out.append("")
    out.append("## Paired differences, semantic entropy minus each alternative (bootstrap 95% CI)")
    out.append("")
    se = [r["se"] for r in ans]
    for name, key in methods[1:]:
        s = [r[key] for r in ans]

        def diff(idx, s=s):
            a = safe_auroc([se[k] for k in idx], [wrong[k] for k in idx])
            b = safe_auroc([s[k] for k in idx], [wrong[k] for k in idx])
            return None if a is None or b is None else a - b
        point = diff(list(range(len(ans))))
        lo, hi, _ = boot_ci(diff, len(ans))
        out.append(f"- vs {name}: {point:+.3f} ({lo:+.3f} to {hi:+.3f})")
    out.append("")
    out.append("## Secondary: correct vs not-correct, all questions (failed counts as not correct)")
    out.append("")
    notc = [r["label"] != "correct" for r in rows]
    for name, key in methods:
        a = safe_auroc([r[key] for r in rows], notc)
        out.append(f"- {name}: AUROC {a:.3f}" if a is not None else f"- {name}: undefined")
    (RES / "RESULTS.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))


if __name__ == "__main__":
    main()
